# Generated by Django 4.2.13 on 2025-12-18 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diseases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseaserecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disease_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="diseaserecord",
            unique_together={("user", "disease_code")},
        ),
    ]
