# Generated by Django 4.2.13 on 2025-12-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_sessions",
                to="files.medicalfile",
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="analysis.analysissession",
            ),
        ),
    ]
