# Generated by Django 4.2.13 on 2025-12-18 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название промта"),
                ),
                ("prompt_text", models.TextField(verbose_name="Текст промта")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("all", "Все типы"),
                            ("image", "Изображения"),
                            ("pdf", "PDF документы"),
                            ("docx", "DOCX документы"),
                            ("text", "Текстовые файлы"),
                            ("dicom", "DICOM файлы"),
                        ],
                        default="all",
                        max_length=50,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промт ИИ",
                "verbose_name_plural": "Промты ИИ",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="detectedcondition",
            name="detected_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detectedcondition",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[("low", "Низкая"), ("medium", "Средняя"), ("high", "Высокая")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AIPromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt_text", models.TextField(verbose_name="Текст промта")),
                ("version", models.IntegerField(default=1, verbose_name="Версия")),
                (
                    "change_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина изменения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем изменено",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="analysis.aiprompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия промта",
                "verbose_name_plural": "Версии промтов",
                "ordering": ["-created_at"],
            },
        ),
    ]
