# Generated by Django 4.2.13 on 2025-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_aiprompt_detectedcondition_detected_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="processing_time",
            field=models.FloatField(default=0.0, verbose_name="Время обработки (сек)"),
        ),
    ]
