# Generated by Django 4.2.13 on 2025-12-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_analysisresult_processing_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectedcondition",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание состояния"),
        ),
    ]
