# Generated by Django 4.2.13 on 2025-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_detectedcondition_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectedcondition",
            name="condition_code",
            field=models.CharField(blank=True, default="UNKNOWN", max_length=50),
        ),
    ]
